server:
  port: 9092
spring:
  application:
    name: grpc-stats-aggregator
  docker:
    compose:
      enabled: true
      file: ./dependencies/grpc-stats-aggregator/compose.yaml
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:foobar}
      username: ${REDIS_USERNAME:foobar}
management:
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: ${ENABLE_TRACES:true}
    sampling:
      probability: ${TRACES_SAMPLING_RATE:1.0}
  otlp:
    tracing:
      endpoint: ${OLTP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
project:
  ui-app:
    hosts: "*"
