server:
  port: 8082
spring:
  application:
    name: grpc-stats-aggregator
  docker:
    compose:
      enabled: true
      file: ./dependencies/grpc-stats-aggregator/compose.yaml
project:
  ui-app:
    hosts: "*"
