server:
  port: 9092
spring:
  application:
    name: grpc-stats-aggregator
  docker:
    compose:
      enabled: true
      file: ./dependencies/grpc-stats-aggregator/compose.yaml
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
project:
  ui-app:
    hosts: "*"
