replicaCount: 1

namespace: spring-projects

nameOverride: grpc-stats-aggregator
fullnameOverride: grpc-stats-aggregator

imagePullSecrets:
  - name: spring-projects-registry-secret

livenessProbe:
  httpGet:
    path: /health
    port: http

readinessProbe:
  httpGet:
    path: /health
    port: http

service:
  port: 8080

podAnnotations:
  linkerd.io/inject: enabled

sealedSecrets:
  enabled: true
  name: &sealed-secret-name grpc-stats-aggregator-secrets
  secrets:
    REDIS_PASSWORD: AgCP3S/VlWUbx0DjgL+hlppABLYx/bW0IW3qdjFiuAOn2XeV1OFiY6n+G1kGry7MiEgg2hzDclfpmXjV3a0ADqJaqxj+k2F9W9FbTxW/ogBseSRKuJX3+rW01c4N9/z+1c1Lp9CFLZ4upAKD9M+NjLDVC9fS6RmjTxUSqC3Nw16zrfaoXXpe6hziPcv2geOOskaU7qh8u7+9Z5m1UYaVMIdMFvhCq5eJmnImEawX2P90mTndNFZmY6zMmAVGjL4z8gGoTanGQgd/34t34ASmD2/4DSrJ9z2RX9vLG9IndxKhK1Zz6dTdkCAmwexrGJm/UIb5I6+6ZqZyZIzCvSoNDAodkhbaJ0bRaOpGaf7es5V9x6gkQakFcjw1ngTnHa8uy3XWoXPdqR5QYIHt0h4B4kkYirwARGhNiGvazvyldEqAgP/tmNzoXvvhiy+oFRHFJ/tTfoq3y471loaWxYuBQgpwpxiCCc3rOyUgvaVGOtcK4O5XJrOojyAPM077OJc0MAOeL7NfOClvoND3zuru7b/tPDESIzs8HyBzqTBiewRpYk/EMtUJ6HHsbuzUa95aaM1phrRfiX2it06CCJ44lUo7lKRJdG2z2CuY2937MnxwU8vnQBh9PFb4PS0QALcoh8TAViGZR0S9O8oeMZhnM0ACbMHRUvOXZUO5nsOqv0ibTseWWaT8EZKBw/Y8P6hcBhl2VuDAY1fmNmIX6BU57eH716dN2OI+OycaN00jpTiRcjIin/etz2PvV7B7Ci2eyAp2QDnl+8fIqrrOWpZQj/L+
    REDIS_USERNAME: AgALlh5w/t8WUb5zBccFbxRyvqk1q2ZV8/nQEAlOa5LTGvcUqOgMZhFVgll0/NKh7Qb7GBb6zgGR9oFSiLzVzcxFNhmJ+HM0G1vBgIzd0/sG0tSzix2fDI1NDA6+An4TQ6z2XR1bQQmDVY/cHFW1zMEvTXUifJoJUBRe9eK2cg/ibQmZvdv3PrHJDKdig1B7Muy842UFMwypjB30nSI5z99Qm8qRH6LDfyv2aIfghijxPTuNhP5RGXGkbGvMCq/E30hfb9Jq5OWi88MVV/3uAsZTIvMN/y/GIbAEEASZYp0m59Zv1JOY+CFNrjkVTHr5myT9uqJgdYAaAC4+/WJtaRMe96mWU9+Wip96bweek57UhSsKBs15a5IKqPf+rCMac64ZxTeh2hAMH/NLs8cYMg4lAEMq+dC1PtkEk0qGKK410+obA1sajkv+BezNnEozukCfAUWPCYUlfPhfC3XYt2cehe/hc4GhnI5tS+bpZTk7ddPyMJsQChR6sAsDOSgmCZcMZUbaSeEJWj/SW6HSnmwAiWznidY47tiF+Tc86S/OeFVGQAjcUNf/BK+EKdL+6i6W+4GlHaZCStcx1+00duhtEv8/EqjPzgqMctO0obokLRbgEphy3ID/hx/3hVXx9Qd8neuAOgKkIgDyvFVfOTjTZ1IH2/n6tUFQyffqISAZXPSiqhg+cWV+RvttODhwtqFxCP284XG9

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: "monitoring"

environmentVariables:
  - name: REDIS_HOST
    value: valkey-primary.valkey.svc.cluster.local
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_DATABASE
    value: "1"
  - name: ENABLE_TRACES
    value: "false"
  - name: SPRING_PROFILES_ACTIVE
    value: production
  - name: TRACES_SAMPLING_RATE
    value: "0.0"
  - name: OLTP_TRACING_ENDPOINT
    value: http://locahost
  - name: REDIS_USERNAME
    valueFrom:
      secretKeyRef:
        key: REDIS_USERNAME
        name: *sealed-secret-name
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        key: REDIS_PASSWORD
        name: *sealed-secret-name
