services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    environment:
      REDIS_ARGS: "--requirepass foobar --user foobar on >password ~* allcommands --user default off nopass nocommands"
