cache:
  key: gradle-cache
  paths:
    - .gradle/
    - build/

spotless-formatting-check:
  image: gradle:8.12.1-jdk23-alpine
  stage: prerequisites
  script:
    - wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
    - wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r1/glibc-2.35-r1.apk
    - apk add glibc-2.35-r1.apk
    - apk add --no-cache libc6-compat
    - ./gradlew --no-daemon spotlessCheck
  interruptible: true

unit-test:
  image: gradle:8.12.1-jdk23-alpine
  stage: prerequisites
  script:
    - ./gradlew --no-daemon test
  interruptible: true

compile-and-build-jar:
  image: gradle:8.12.1-jdk23-alpine
  stage: build
  script:
    - ./gradlew --no-daemon clean build -x spotlessCheck test
  interruptible: true
