cache:
  key: gradle-cache
  paths:
    - .gradle/
    - build/

spotless-formatting-check:
  image: gradle:8.12.1-jdk23-alpine
  stage: prerequisites
  script:
    - apk add --no-cache libc6-compat
    - apk add libatomic
    - ./gradlew --no-daemon spotlessCheck
  interruptible: true

spotless-formatting-check-2:
  image: gradle:8.12.1-jdk23-alpine
  stage: prerequisites
  script:
    - apk add --no-cache libc6-compat
    - ./gradlew --no-daemon spotlessCheck
  interruptible: true

docker-build:
  image: jburgess/gradle-protoc:latest
  services:
    - docker:18.09.7-dind
  stage: prerequisites
  script:
    - ./gradlew --no-daemon spotlessCheck


#
#unit-test:
#  image: gradle:8.12.1-jdk23-alpine
#  stage: prerequisites
#  script:
#    - ./gradlew --no-daemon test
#  interruptible: true

compile-and-build-jar:
  image: gradle:8.12.1-jdk23-alpine
  stage: build
  script:
    - ./gradlew --no-daemon clean build -x spotlessCheck test
  interruptible: true
